version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3-management
    hostname: "hotel-rabbitmq"
    container_name: hotel-rabbitmq
    volumes:
     - ./etc/definitions.json:/etc/rabbitmq/definitions.json
     - ./etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.config
     - ./data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
     - ./logs:/var/log/rabbitmq/log
    ports:
     - 5672:5672
     - 15672:15672

  mongo:
    image: mongo
    container_name: hotel-mongo
    restart: always
    environment:
     MONGO_INITDB_ROOT_USERNAME:
     MONGO_INITDB_ROOT_PASSWORD:
    volumes:
     - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: hotel-mongo-express
    restart: always
    ports:
     - 8081:8081
    environment:
     ME_CONFIG_MONGODB_ADMINUSERNAME:
     ME_CONFIG_MONGODB_ADMINPASSWORD:
    depends_on:
     - mongo

  hotel.apigateways.main:
    build:
     context: .
     dockerfile: Source/ApiGateways/Hotel.ApiGateways.Main/Dockerfile
    image: hotel-main-apigateway
    container_name: hotel-main-apigateway
    ports:
     - 6000:80
    restart: on-failure
    depends_on:
     - rabbitmq

  hotel.services.identity:
    build:
     context: .
     dockerfile: Source/Services/Hotel.Services.Identity/Dockerfile
    image: hotel-identity-service
    container_name: hotel-identity-service
    ports:
     - 6001:80
    restart: on-failure
    depends_on:
     - rabbitmq
     - mongo

  hotel.services.financial:
    build:
     context: .
     dockerfile: Source/Services/Hotel.Services.Financial/Dockerfile
    image: hotel-financial-service
    container_name: hotel-financial-service
    ports:
     - 6002:80
    restart: on-failure
    depends_on:
     - rabbitmq
     - mongo

  hotel.services.reservation:
    build:
     context: .
     dockerfile: Source/Services/Hotel.Services.Reservation/Dockerfile
    image: hotel-reservation-service
    container_name: hotel-reservation-service
    ports:
     - 6003:80
    restart: on-failure
    depends_on:
     - rabbitmq
     - mongo